import { NgModule } from '@angular/core';
import { KeysPipe } from './keys.pipe';
import { GetByIdPipe } from './getById.pipe';
import { HtmlToPlaintextPipe } from './htmlToPlaintext.pipe';
import { FilterPipe } from './filter.pipe';
import { CamelCaseToDashPipe } from './camelCaseToDash.pipe';
import { LimitToDirective } from '@fuse/services/limitTo';
import {
    TimeFormatPipe,
    FilterCountryDataPipe,
    FilterDivisionDataPipe,
    FilterPestTypeDataPipe,
    FilterJobTypeDataPipe,
    FilterPaymentTermDataPipe,
    FilterPaymentModeDataPipe,
    FilterBillingFrequencyDataPipe,
    FilterEnquiryNumberDataPipe,
    FilterCoverageAreaDataPipe,
    FilterScheduleFrequencyDataPipe,
    FilterWorkOrderDataPipe,
    FilterContractDataPipe,
    FilterSupplierDataPipe,
    FilterCategoryDataPipe,
    FilterUnitDataPipe,
    FilterStoreDataPipe,
    FilterProductNameDataPipe,
    FilterWorkOrderReferenceDataPipe,
    FilterCurrencyDataPipe,
    FilterPurposeDataPipe,
    FilterManufacturerDataPipe,
    FilterDepreciationDataPipe,
    FilterMaintenanceTypeDataPipe,
    FilterStatusDataPipe,
    FilterAssetModelDataPipe,
    FilterTeamNameDataPipe,
    FilterClientNamePipe,
    FilterUOMDataPipe,
    FilterProcessStageDataPipe,
    FilterColorDataPipe,
    FilterStyleDataPipe,
    FilterOrderNameDataPipe,
    FilterDiaDataPipe,
    FilterFabricDataPipe,
    FilterGsmDataPipe,
    FilterLotNoDataPipe,
    FilterLineNoDataPipe,
    FilterCategoryPipe,
    FilterAccessoriesPipe

} from '@fuse/services/pipe';

@NgModule({
    declarations: [
        KeysPipe,
        GetByIdPipe,
        HtmlToPlaintextPipe,
        FilterPipe,
        CamelCaseToDashPipe,
        LimitToDirective,

        TimeFormatPipe,

        FilterClientNamePipe,
        FilterUOMDataPipe,
        FilterProcessStageDataPipe,
        FilterColorDataPipe,
        FilterStyleDataPipe,
        FilterOrderNameDataPipe,
        FilterDiaDataPipe,
        FilterFabricDataPipe,
        FilterGsmDataPipe,
        FilterLotNoDataPipe,
        FilterLineNoDataPipe,

        FilterCountryDataPipe,
        FilterDivisionDataPipe,
        FilterPestTypeDataPipe,
        FilterJobTypeDataPipe,
        FilterPaymentTermDataPipe,
        FilterPaymentModeDataPipe,
        FilterBillingFrequencyDataPipe,
        FilterEnquiryNumberDataPipe,
        FilterCoverageAreaDataPipe,
        FilterScheduleFrequencyDataPipe,
        FilterWorkOrderDataPipe,
        FilterContractDataPipe,
        FilterSupplierDataPipe,
        FilterCategoryDataPipe,
        FilterUnitDataPipe,
        FilterStoreDataPipe,
        FilterWorkOrderReferenceDataPipe,
        FilterProductNameDataPipe,
        FilterPurposeDataPipe,
        FilterCurrencyDataPipe,
        FilterManufacturerDataPipe,
        FilterDepreciationDataPipe,
        FilterMaintenanceTypeDataPipe,
        FilterStatusDataPipe,
        FilterAssetModelDataPipe,
        FilterTeamNameDataPipe,
        FilterCategoryPipe,
        FilterAccessoriesPipe
    ],
    imports: [],
    exports: [
        KeysPipe,
        GetByIdPipe,
        HtmlToPlaintextPipe,
        FilterPipe,
        CamelCaseToDashPipe,
        LimitToDirective,

        FilterClientNamePipe,
        FilterUOMDataPipe,
        FilterProcessStageDataPipe,
        FilterColorDataPipe,
        FilterStyleDataPipe,
        FilterOrderNameDataPipe,
        FilterDiaDataPipe,
        FilterFabricDataPipe,
        FilterGsmDataPipe,
        FilterLotNoDataPipe,
        FilterLineNoDataPipe,

        TimeFormatPipe,
        FilterCountryDataPipe,
        FilterDivisionDataPipe,
        FilterPestTypeDataPipe,
        FilterJobTypeDataPipe,
        FilterPaymentTermDataPipe,
        FilterPaymentModeDataPipe,
        FilterBillingFrequencyDataPipe,
        FilterEnquiryNumberDataPipe,
        FilterCoverageAreaDataPipe,
        FilterScheduleFrequencyDataPipe,
        FilterWorkOrderDataPipe,
        FilterContractDataPipe,
        FilterSupplierDataPipe,
        FilterCategoryDataPipe,
        FilterUnitDataPipe,
        FilterStoreDataPipe,
        FilterWorkOrderReferenceDataPipe,
        FilterProductNameDataPipe,
        FilterCurrencyDataPipe,
        FilterPurposeDataPipe,
        FilterManufacturerDataPipe,
        FilterDepreciationDataPipe,
        FilterMaintenanceTypeDataPipe,
        FilterStatusDataPipe,
        FilterAssetModelDataPipe,
        FilterTeamNameDataPipe,
        FilterCategoryPipe,
        FilterAccessoriesPipe
    ]
})
export class FusePipesModule { }
